### ISSUE TITLE
Pokeball Ratio

### ISSUE THREAD

**Issue by eyeball3r** [NECROBOTIO/NecroBot#1670]
Not so much an issue, I think... But it appears that the automatic inventory control of the Pokeballs favours more to the Pokeballs... Whilst the Great/Ultra balls are kept to a minimum. Is it possible to regain full control over the quantities?

Awesome work so far otherwise!

**Comment by chimichandra** [comment]
Yep, same here. Suspect it has something to do with the new IV and cathc probability settings. changing them does NOT solve anything.

**Comment by Aneduna** [comment]
Set these Values in the settings, happening because #1678 
"UseGreatBallAboveCp": 1000,
"UseUltraBallAboveCp": 1250,
"UseMasterBallAboveCp": 1500,
"UseGreatBallAboveIv": 85,
"UseUltraBallAboveIv": 90,
"UseGreatBallBelowCatchProbability": 0.3,
"UseUltraBallBelowCatchProbability": 0.2,
"UseMasterBallBelowCatchProbability": 0.05,

or customize the settings
