### ISSUE TITLE
[Suggestion] CP, iv & Potions, pokeballs

### ISSUE THREAD

**Issue by li81** [NECROBOTIO/NecroBot#1862]
Hello, I have 2 suggestions:

1. Add back the old style of deleting potions and pokeballs, currently it's keeping the shitty ones. Basicly when you have 100 potions declared, and you have 80 revives, there is only 20 spots left for other potions.

2. Currently the iv & CP aren't working together. It's either good iv with low cp or good CP with bad iv.
Current config:
"Snorlax": {
      "KeepMinCp": 2300,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 5
    },
"KeepMinDuplicatePokemon": 1,
PokemonsNotToTransfer = empty.

It keeps every snorlax above 95.0 iv OR above 2300 CP. "KeepMinDuplicatePokemon": 5 doesn't work as I have over 5 snorlax now, see picture. 
![1234](https://cloud.githubusercontent.com/assets/1375379/17304835/e4beb120-5827-11e6-8396-b19b8501a929.jpg)

Make them work together so we can keep good CP with good iv and 5 of the same pokemon (depends on how many u put in config file to keep ofcourse)

**Comment by recon88** [comment]
For point 1 see #1702

**Comment by DeityOfChaos** [comment]
I think the CP/IV thing is working fine - It says 'KeepMinCp' and 'KeepMinIvPercentage' and that's actually what it is doing. It does not combine both into one as it probably would send a lot of high IV / high CP pokemons to hell.

**Comment by li81** [comment]
So, forever stuck with a snorlax of 100cp and 95% iv? -_-

**Comment by Algent** [comment]
Ok, since my issue was a duplicate (I didn't find this one) I'll continue here.

I'm also really interested in this, it would be much easier to manage.
Right now the KeepMinCp and KeepMinIvPercentage can easily get out of control:
- For "strong" ones (Lot of CP) You end up with a lot of untransfered guys
- For "weak" one (Those with low CP) unless you set dedicated filter for each you end up with either best CP or best IV depending on your setting.

As I said in #1880 :
> Something like "KeepMinBestBothIvAndCp: true".
Maybe allow it to be set globally and in a PokemonsTransferFilter. 

It could also be a value for those who want to keep more than one each.

@GediminasMasaitis About your question on "KeepMinDuplicatePokemon" you asked on the other issue, I think if enabled this new setting should override it, it wouldn't work if it didn't.

**Comment by qzqzqz** [comment]
KeepMinDuplicate does work. 
If its set to 5, it keeps at least 5, no matter if their CP or iv is lower than in MinCp oder Minivpercentage requested.
So if you dont want that Snorlax with 95% iv and 100cp, which in my opinion is pretty legit, you should higher the minivpercentage.
but be careful, if a high cp snorlax doesnt fulfill the 2300CP, it gets deleted.

**Comment by li81** [comment]
It's not working see screenshot. It's already over 5 snorlax count. Also I already have "KeepMinIvPercentage": 95.0. 

As I said before: 
Make them work together so we can keep good CP with good iv and 5 of the same pokemon (depends on how many u put in config file to keep ofcourse)

**Comment by SwoleSnorlax** [comment]
I also have the same problem as li81, my dragonites, chanseys, lapras, snorlax, etc. all stack up even though I set duplicates to a low number.

**Comment by Furyslayer** [comment]
I was hoping the individual filter would be cp AND iv to keep...not cp OR IV.  It would be great if i could set it to only keep 95% or higher snorlax that are already 2500+
