### ISSUE TITLE
EncounterPokemonFled

### ISSUE THREAD

**Issue by SpartaGH** [NECROBOTIO/NecroBot#1952]
error EncounterPokemonFled

**Comment by OliSando** [comment]
I'm also receiving this error :-1:

**Comment by mpew** [comment]
I.m receiving this : (ATTENTION) Encounter problem: EncounterNotFound

**Comment by kingchenc** [comment]
i get too ecounter problem, bot run very slow with that..
what meant the bot with that?

[04:03:38] (ATTENTION) Encounter problem: EncounterNotFound

**Comment by SwoleSnorlax** [comment]
(ATTENTION) Encounter problem: EncounterNotFound also getting this error

**Comment by sigitpadi** [comment]
same here, please help

**Comment by daniloso92** [comment]
Same here, please help...

**Comment by senakek** [comment]
Apparently I read in another thread/forum (can't remember) to temporarily fix this you have to change your location, but it would be nice to go back to your original area since there's a lot more Pokemon to catch in these areas. 

BUT: Changed my location and had it running for about 30 mins and it started happening again
