### ISSUE TITLE
[BUG] Pokemon not transferring?

### ISSUE THREAD

**Issue by ItsLost** [NECROBOTIO/NecroBot#1991]
So, uh yea. Full Pokeman inventory, won't transfer pokemon AT ALL!
https://gyazo.com/138dfbdb267b82b0741a51dc1eb7e0da
https://gyazo.com/2db4f5665e202b86c1177f8bbae8b116
https://gyazo.com/0473ad6775a7fb26c2002374d681a8a7

**Comment by Wcidd** [comment]
Check "PokemonsNotToTransfer":

**Comment by cbnolok** [comment]
Same for me, i pulled and compiled today, it doesn't transfer pokemons in the list, while with yesterday pull it worked

**Comment by Ryzison** [comment]
looking through your config settings I can only assume all of your pokemon meet the requirements of 'above CP 300" and "above 30% perfect iv's" and your inventory is full of them. 

I suggest raising KeepMinCp to a CP higher than 300, and KeepMinIvPercentage to higher than 30%
for example my KeepMinCp is set to 2000 so it doesn't keep duplicates unless they're over 2000 CP and my KeepMinIvPercentage is set to 90.0 so that it doesn't keep any duplicates under 90% perfect IV's

**Comment by ItsLost** [comment]
Thanks Ryzison ^-^

**Comment by Blemmer123** [comment]
I had the same problem with some of my pokemon. I had the following settings:

  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 2000,
  "KeepMinIvPercentage": 95.0,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": false,
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": false,

With these settings I keep 1 of every type AND any pokemon above 95 IV OR above 2000 IV. For some reason though, mostly low level pokemon (rattatas/pidgeys/weedles) did not transfer. 

I found a fix: It seems that the bot didnt transfer the pokemon that were on the PokemonsToEvolve list, even though KeepPokemonThatCanEvolve was set to false. SO I emptied the list, and from that moment on all pokemon got transferred again.

I dont know how to fix this in the code, but I figured this could help the developers fixing this bug.

**Comment by darkzurvan** [comment]
I'm having the same, or at least a similar problem, since this morning. Pokemon in the PokemonsTransferFilter transfer properly, but nothing else will transfer. For clarity, relevant settings are set to:

"KeepPokemonsThatCanEvolve": true,
  "KeepMinCp": 1300,
  "KeepMinIvPercentage": 95.0,
  "KeepMinOperator": "and",
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,
...
"TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": false,

I've played with the last couple a few times, I lost a lot of pokemon that I only have one of when "TransferWeakPokemon" was set to true by default, and "TransferDuplicatePokemonOnCapture" only affects the PokemonsTransferFilter list. In my frustration and utter lack of coding knowledge, I'm guessing that some of the new settings are conflicting.
