### ISSUE TITLE
NecroBot Crashes after an hour or two

### ISSUE THREAD

**Issue by nisanb** [NECROBOTIO/NecroBot#1997]
Hi !
I've been running a few instances of NecroBot simultaneously and since the last updates it's been crashing (all of them).
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	NecroBot.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	579ce5a5
  Problem Signature 04:	Google.Protobuf
  Problem Signature 05:	3.0.0.0
  Problem Signature 06:	578f77a6
  Problem Signature 07:	14d
  Problem Signature 08:	e
  Problem Signature 09:	System.ArgumentNullException
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	d1d9
  Additional Information 4:	d1d94a13d3609d6b740644c12508f581

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by ANR2ME** [comment]
@nisanb are you using PTC or Google login?
I also gets crashes quite often after running it for a few hours (PTC login), while an old version (0.1.6 i think) was very stable (i can run it for days without crashing, although the console showing a lot of exception but it didn't crashed the program and will eventually worked properly again).

Probably in newer version there could be some uncaught exception during [re]login, since most of the time the console showing Exception at Login.cs before crashing the program.

**Comment by recon88** [comment]
ArgumentNullException should be fixed in the next release.
