### ISSUE TITLE
Ultraballs,greatballs get used first .

### ISSUE THREAD

**Issue by SDMU** [NECROBOTIO/NecroBot#2105]
All my ultra balls and then the great balls get used first . Only after that do my poke balls get used . I even specified the IV and CP values for which the ultra and great balls must be used in the .config file . Inspite of that my ultra and great balls are used first . Can you please provide a solution ?

**Comment by nfettinger** [comment]
Please make sure you are using a recent config.json. New values are configurable for which balls are used.

**Comment by theloser** [comment]
This is a config issue, not a development issue. Go to the discord channel to get help, thanks.

**Comment by progz** [comment]
It's probably because of your config.json !
I use this part for my pokebal.
`  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1400,
  "UseMasterBallAboveCp": 2300,
  "UseGreatBallAboveIv": 80,
  "UseUltraBallAboveIv": 90,
  "UseGreatBallBelowCatchProbability": 0.3,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.01,
`

**Comment by SDMU** [comment]
Thank you nfettinger, theloser , progz . The problem was that I was inserting the percentages in the probability values , for eg for 10% chance , I wrote 10 instead of 0.1  . Damn, I feel so stupid now . So many balls wasted :(
