### ISSUE TITLE
Sniping while ignoring unknown IVs

### ISSUE THREAD

**Issue by RichardZhaoE** [NECROBOTIO/NecroBot#2210]
"SnipeIgnoreUnknownIv" set true or false both will snipe unknown IVs.

**Comment by degree8th** [comment]
Add leave catch if IV below then "KeepMinIvPercentage" in config, when sniping unknown IVs.

**Comment by OperativeLoop** [comment]
Could be the UseTransferIvForSnipe setting. I just looked at its usages and it seems like the only usage of that value is if its false it ignores the SnipeIgnoreUnknownIv value. 

 (!session.LogicSettings.UseTransferIvForSnipe ||
                             (q.IV == 0 && !session.LogicSettings.SnipeIgnoreUnknownIv) ||
                             (q.IV >= session.Inventory.GetPokemonTransferFilter(q.Id).KeepMinIvPercentage)

That's from where its selecting the snipe locations, I think UseTransferIvForSnipe should just be removed, since it doesn't do anything when true and when its false it messes up sniping.

**Comment by rherartt** [comment]
i cant make sniping work, can you guys show me your sniping settings?

**Comment by NecronomiconCoding** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
