### ISSUE TITLE
Instead of evolving pokemon, bot transfers them

### ISSUE THREAD

**Issue by Behated** [NECROBOTIO/NecroBot#2314]
Bot is set not evolving all possible pokemon but instead it chooses to transfer some. As shown in the picture below I got more than 12 candies that it requires to evolve a pidgey but it goes ahead and transfers them. 

  "EvolveAboveIvValue": 0.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,

Bot version: v0.6.2

![350f02ecf9074ab08ee4d46e805ef4cf](https://cloud.githubusercontent.com/assets/20804707/17348978/1c8cbb8c-5923-11e6-9ff7-9883a1ab8af4.png)

**Comment by proesd** [comment]
confirmed, I think it's only happened to pidgey after evolve, not the all, but the others is strange
First
![pid](https://cloud.githubusercontent.com/assets/20630687/17349309/c9dbd67e-5946-11e6-8fd5-bcf47cc5fd36.png)
Ssecond
![pidg](https://cloud.githubusercontent.com/assets/20630687/17349313/d6b9a98e-5946-11e6-8e8b-f270e2879ab8.png)

**Comment by simplyphp** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki/Config
KeepPokemonsThatCanEvolve (Value)

When NecroBot determines how many Pokemon to transfer due to duplicates, it will create a count based on the number of candies the account has for that species compared to the number required to evolve.

For example, if the account has 5 Pidgeys (12 candies to evolve) and 24 candies, NecroBot will keep the top two Pidgeys and transfer the rest.

**Comment by Behated** [comment]
![image](https://cloud.githubusercontent.com/assets/20804707/17371320/1c4c15ca-59a8-11e6-85a2-80c73ea90bfa.png)

  "KeepPokemonsThatCanEvolve": true

Something I am missing?

I transfers A LOT of pidgeys instead of evolving while "KeepMinDuplicatePokemon": 1

**Comment by whiteshark-1975** [comment]
that seems to be normal he has to transfer some to get candies when enough candies he can evolve some
you get 3 candies for catching +1 for transfer you need way more to evolve so he cant keep them all
.

**Comment by IamAii** [comment]
Some of mine I have 500-800 candies and I can not get them to evolve. They were the first day I ran the script 2 days ago, now they no longer evolve they just transfer.

**Comment by aapikz** [comment]
same issue i have 1k pidgey candies and it only evolves 4 to 5 of them and the rest of pidgey transfer it .. wierd

**Comment by actislav** [comment]
bot uses caches for most of its server requests (and refresh them with 30 sec delay), and your case can be real because of it, you caught last pidgey(pidgeys) just before evolve task, that is why they are not in cached storage and evolve task just did not see it, but when transfer task started cache updated, and new* pidgeys was transfered

**Comment by actislav** [comment]
Behated i think if u dump your pokemon list you will see the reason = you already have in storage pokemon to evolve with your count of candy, and bot is just waiting the moment to make mass evolve then your storage will be filled enough, see  EvolveKeptPokemonsAtStorageUsagePercentage parameter
