### ISSUE TITLE
[Question] KeepMinIvPercentage

### ISSUE THREAD

**Issue by cwirek91** [NECROBOTIO/NecroBot#2411]
"KeepMinCp": 5000,
"KeepMinIvPercentage": 100.0,
"KeepMinOperator": "or",

I want to keep Pokemons only which have 100% IV. Should I set KeepMinIvPercentage 100.0 or 99.9?

**Comment by ANR2ME** [comment]
Based on the wiki (which already detailed enough) "This value specifies that a Pokemon that has an IV higher than this value will not be transferred.", so you should use the value lower than 100%

The only new setting is probably "KeepMinOperator" where you may need to changed it to "and" and lower the KeepMinCP value, otherwise it will keep any pokemons with CP 5000 (if any) regardless the IV

**Comment by cwirek91** [comment]
Ye i know it, i read wiki but if something is minimun so its '>=' 100, not like EvolveAllPokemonAboveIv where is text 'above' which should means '>'.
