### ISSUE TITLE
QUESTION : Value of UseLuckyEggsMinPokemonAmount

### ISSUE THREAD

**Issue by Artixia** [NECROBOTIO/NecroBot#2458]
Hi,

When I launched the bot this morning , I had the value of UseLuckyEggsMinPokemonAmount 90 .
I was 71 Pokemon that can evolve but has nevertheless evolved without using lucky eggs (probably because the value was 90 ) .

Once the Pokémon were evolved , the bot tells me : "Lucky eggs will never be used with UseLuckyEggsMinPokemonAmout set to 90 , use < = 43 instead" .

Why I can not put 90 and why they evolved ? ( As there were only 43 ? No candy because I had put 90 I suppose? )

Why the bot evolve  pokemon one by one while i have " EvolveAllPokemonWithEnoughCandy" set to true and "UseLuckyEggsMinPokemonAmount" set to 90 ?

Thanks

**Comment by Taranis01** [comment]
Is your pokemon inventory very full? Because then it will conflict with   "EvolveKeptPokemonsAtStorageUsagePercentage":  causing to evolve pokemons in order to keep space. make sure to keep   "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0, on a number >90 and that unimportant pokemons get transfered

**Comment by Artixia** [comment]
Oh, the value " EvolveKeptPokemonsAtStorageUsagePercentage " is automatically set to 20, why?
so I have put it at 90 ?

**Comment by Taranis01** [comment]
yes try that :)

**Comment by Wcidd** [comment]
Config setup wrong, not bot error
