### ISSUE TITLE
Keep best IV and another with best CP?

### ISSUE THREAD

**Issue by FatmaBlub** [NECROBOTIO/NecroBot#2513]
Hey there,

I opened this thread two days ago, and it was closed because of a similar thread - BUT the thread was dealing with something else. So here's my issue again:

I wondered if there is an option, to keep both the best IV and the best CP Pokémon (meaning I keep at least **two Pokémon of each**)! 
For example: If I catch 5x Pikachu like listed below, I want to keep the one with the best CP **and another** with the best IV. In this case this would be P5 (best CP) and P4 (best IV).
P1 = LvL 22, CP 730, IV 70%
P2 = LvL 22, CP 721, IV 63%
P3 = LvL 22, CP 661, IV 74%
P4 = LvL 22, CP 571, IV 82%
P5 = LvL 22, CP 773, IV 40%
The other Pikachus could be transferred. In the config.json I already changed the "KeepMinDuplicatePokemon"-Value to 2. But right now the Bot just keeps the Pokemon, who fits the best in whatever category. In my example above that could mean, the Bot keeps P1 and P5 (both high CP) - but I'd like to have one with highest CP >and another< with highest IV :)

Does someone know, whether this is possible?
Otherwise it would be a really nice option to add!

**Comment by nfettinger** [comment]
Why not just power up your best two IV pokemon to have higher CPs?

**Comment by Taranis01** [comment]
@nfettinger that way you'd make sure that you still keep your higher CP (at this time) Pokemon as long the higher IV Pokemon is not upgraded. It will prevent that your pokemon inventory is crowded with the same pokemon because in order to keep the highest CP pokemon ONLY you need to edit KeepMinCP manual right now.

See also https://github.com/NECROBOTIO/NecroBot/issues/2312#event-743656850
( i would change my suggestion to use a global setting instead of an individual though)
