### ISSUE TITLE
Only using berries on first attempt

### ISSUE THREAD

**Issue by Agger84** [NECROBOTIO/NecroBot#2543]
When all my criteria is met for using a berry it will only throw 1 berry on the first attempt. For any subsequent attempts, no berries are used.

**Comment by djdookie** [comment]
I can confirm this behaviour.
This was changed some releases ago, and I thought it's possibly intended, because a berry only needs to be used in the beginning and not for every ball thrown? Don't know the exact PoGo-Mongo rules! ;)

**Comment by prateekkarki** [comment]
Is it really the case? I think Berries need to be used after every unsuccessful attempt. 
I think so because in the game, you cannot use berries if you miss the pokemon right after using a berry. Although if its an unsuccessful attempt and the pokemon breaks free, you are allowed another berry. 
I think niantic do want the players to use multiple berries that way.
