### ISSUE TITLE
What thet point and logic "KeepMinDuplicatePokemon": 1, inside   "PokemonsTransferFilter": {

### ISSUE THREAD

**Issue by vipery** [NECROBOTIO/NecroBot#2577]
I have bunch of Snorlax kept. Snorlax is not NotToTransfer list. What the point and Logic?

    "Snorlax": {
      "KeepMinCp": 2100,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },

Snorlax	25	2161	79.2300942874937
Snorlax	23	2031	94.7127941065701
Snorlax	17	1511	100
Snorlax	14	1234	93.5894220164711
Snorlax	11	976	98.0727974258185
Snorlax	6	509	94.2034332208115
Snorlax	5	419	98.8787982329142
Snorlax	5	417	96.6313480092522
Snorlax	4	322	92.1160467795413
Snorlax	1	43	90.5466491115821

Cool i have tons of 90 + IV Snorlax. But i want keep only one, max two. Im already Set   "KeepMinDuplicatePokemon": 1, to 0, to two. And still have bunch of Snorlax. Someone explain.

**Comment by casselc** [comment]
So this filter basically says:
Keep at least 1 (``KeepMinDuplicatePokemon``) Snorlax,
Discard duplicate Snorlax UNLESS the duplicate has at least 2100CP (``KeepMinCp``) OR (``KeepMinOperator``) is greater than 90% IV (``KeepMinIvPercentage``)

All of the Snorlax you have listed are above 2100CP or 90IV, so it looks like it's working as expected. You could try either raising ``KeepMinCp`` or ``KeepMinIvPercentage``, adding a preferred move set, or change the ``KeepMinOperator`` so that the duplicates have to be > 2100CP and > 90IV

Ideally there would be an additional KeepMaxDuplicatePokemon parameter to only keep the x best Pokemon, but based on the other open issues there are bigger problems with the transfer filters at the moment.

**Comment by Marsinator** [comment]
all of your pokemon are above IV except for one, which is above your CP limit.
if you want to have them to be above both values, you need to use "KeepMinOperator": "and"
