### ISSUE TITLE
v0.7.7 logging in issue

### ISSUE THREAD

**Issue by taihangy** [NECROBOTIO/NecroBot#3455]
I have an issue I can't logging in using v0.7.7 since this afternoon.

**Comment by djdookie** [comment]
Same here, Login working in v0.7.6 hangs at "(INFO) Logging in using Ptc" in v0.7.7.
Guys you should really test your "optimizations"! ;)

**Comment by vfuyong** [comment]
Set LoginSuccessProbability = 1

**Comment by djdookie** [comment]
Ok this seemed to be a problem with the servers.
After debugging the code, (for me) the reason was that no ptc authtoken was returned.
Unfortunately the client just said nothing, didn't catch the correct exception and just tried again 20 seconds later via default exception case. No message, no logging. Very bad for the user! ;)
I will try to optimize this behaviour. But this failure is hard to test because meanwhile the servers work fine again. ^^
