### ISSUE TITLE
  "KeepPokemonsThatCanEvolve" logic

### ISSUE THREAD

**Issue by KralElite** [NECROBOTIO/NecroBot#3498]
What is the logic behind   "KeepPokemonsThatCanEvolve".

Is it that it will keep pokemon after they are evolved or will it keep pokemon until they are evolved (lucky egg limit) and then transfer after!?

**Comment by ChemiHatake** [comment]
it will keep the amount of pokemon according to the available candies.
for example:
if you have 5 rattatas and only 75 rattata candy,
it will transfer two of them.

**Comment by MishoAbS** [comment]
and what about its relation with KeepMinDuplicatePokemon? 
For example, if the account has 5 Pidgeys (12 candies to evolve) and 36 candies, NecroBot should keep the top 3 Pidgeys and transfer the rest;
but if KeepMinDuplicatePokemon is 2; 
it should keep 2 or 3 Pidgeys ?
since what i noticed its keeping only 2 for me!

**Comment by nfettinger** [comment]
Duplicate #3244
