### ISSUE TITLE
[0.8.0] Softban after some minute running

### ISSUE THREAD

**Issue by hunghh242** [NECROBOTIO/NecroBot#3645]
I got soft ban after use the bot to catch and get items from poketstops. Anyone have same issues?

**Comment by KillerOffers** [comment]
Yes we all have the same problem!

**Comment by loneable** [comment]
for one your not susposed to have pokemon go opened while the bot is running and also do yall people not know that if your soft banned all you have to do is go up to a pokestop and spin it and back out of it and spin it again 40 times then you wont be banned anymore

**Comment by loneable** [comment]
yea dislike it because your think its a troll but guess what its not go try it and tell me the resualts

**Comment by StarvingDeveloper** [comment]
My bots tried spin 45 times, but still softban. No big deal, since it was fresh bots, but be afraid bot today on old accounts.

**Comment by loneable** [comment]
no i mean you close all the bots and go on the game manually and go to a pokestop and spin it 40 times i do it everytime im softbanned and it works but if yall dont believe me then have fun being banned i guess just trying to help

**Comment by blackuGT** [comment]
Yup, still softbannsss...

**Comment by StarvingDeveloper** [comment]
Or maybe we just asked to agree we do not drive while playing - I doubt any bot can do that atm. Anyone tested login via phone to check what's going on?

**Comment by blackuGT** [comment]
Bot is broken and softbanning instantly ;p

**Comment by parbonature** [comment]
im still running..yeayy....

**Comment by StarvingDeveloper** [comment]
My bots back to normal after 30 min offline. Still dont know what it was. Walking speed just 31km/h, ist it count as driving?

**Comment by WuddyMarco** [comment]
Notice the same Problem. Bot works fine for a few minutes. Getting Softban and cant remove it the spinning way. He tries again and again moves to another pokestop to try again and so on. Restarting the bot results in a "harder" ban where he isn´t even able to find pokestops. Waiting for a few minutes lets the bot work normaly again and so on. 
Maybe it wont be possible to go against that habbit because no pokestop means no unban and so on. I will try to find out how long the bot has to be offline to get around this and maybe we could implement this as waiting time if the bot can´t find any stops after softban.
