### ISSUE TITLE
No pokestops found in your area. Is your maximum distance too small?

### ISSUE THREAD

**Issue by situ1994** [NECROBOTIO/NecroBot#3690]
It was working fine before one minute and now it shows this error? Am I banned or something?

**Comment by brightjoyy** [comment]
Me too, i don't know why

**Comment by Blaucide** [comment]
Have you more than 3 NecroBot oopen?

**Comment by jarpoks** [comment]
same here, happened after restarting necrobot. only running 1 bot atm

**Comment by WuddyMarco** [comment]
Please stop opening the issues and search for the related one. There are already 2 issues openend und much more with the same habbit. It could be related to the maximum distance but i think its an IP ban because of to many bots simultaneously. At the moment two bots at different locations work just fine. Try to wait for about 5 minutes and then try again with max 2 bots and different location.

**Comment by situ1994** [comment]
I had 3 open not more than that. I closed all of them and now opened 1 after few minutes its working
