### ISSUE TITLE
How do you run 2 bots at the same time?

### ISSUE THREAD

**Issue by Jordano3710** [NECROBOTIO/NecroBot#3762]
Could you please tell me how i do 2 bots at the same time?

**Comment by head0r** [comment]
Copy your Bot folder and change the auth file in the copied one. then just start the exe from each folder.

**Comment by Jordano3710** [comment]
What do you mean change the auth file?

**Comment by Yiudorai** [comment]
auth file has your login information. you need to change them to your 2 account

**Comment by Jordano3710** [comment]
Oh yeah got it

**Comment by fass1993** [comment]
you will get softbanned ;)

**Comment by necr-0** [comment]
Rather than you lot complaining about multiple bots not working, I want to make this apparant.
Running multiple bots at the same time on the same IP seems to be chucking up multiple errors related to "No usable PokeStops found in your area". Further to this, as @fass1993 said, it's also leading to softbans.

So if you get these errors, don't complain, you've been warned.

**Comment by Zierk59** [comment]
^multiple bots works for me good.

**Comment by MetaExtreme** [comment]
2 bots are the maximum for 1 IP.
For other accounts you have to use a proxy.

**Comment by necr-0** [comment]
@Zierk59, 

Emphasis on my use of the word "seems". It's not happening to everyone, but nonetheless, it's undeniably happening.

**Comment by ExarSenpai** [comment]
This is why Niantic will look more deeply to stop the bots, because You have to run multiple accounts on the same IP. Can't You just use the 1 account for Your own and not sell others? Like when there is coming only 1 request from the one IP, they won't dig that much.
