### ISSUE TITLE
Dratini evolution 

### ISSUE THREAD

**Issue by joeyd55** [NECROBOTIO/NecroBot#3957]
I seem to only get Dragonair from Dratini. Doesn't evolve past there. Configuration is set at default besides lat and long. Have several Dragonair now.

**Comment by theloser** [comment]
Check your "PokemonsToEvolve" list.

**Comment by CakeHole83** [comment]
Think alittle before asking and dont put this as an issue. It doesnt evolve further because it uses 25 candies to evolve a dratini and needs 100 to evolve to a dragonite. Which means it will never get to dragonite cause it evolves into dragonair for every candy you get.

**Comment by theloser** [comment]
@CakeHole83 You are wrong. If he has 200 candies for Dratini, but he has nether Dratini nor Dragonair. If he catches a Dratini it will get evolved. And, because now he has a Dragonair it will be evolved, too. Or if he catches a Dragonair of course it will be evolved (if his configuration is setup correctly).

And, before you ask: of course he can get 200 candies easily if he catches a lot of Dragonites and transfers them :-)

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
