### ISSUE TITLE
Recycle all types of balls

### ISSUE THREAD

**Issue by chinpun** [NECROBOTIO/NecroBot#3958]
I m working with the bot but i have a problem, the bot its recycling all the time pokeballs because i have many superballs and ultraballs, can i add some option in the config to keep only some of each type?

**Comment by chimichandra** [comment]
Why would you want this? Ultraballs are better than greatbalss that are better than pokeballs. Why would you want to recycly ultraballs when you have pokeballs?

**Comment by AxiomCro** [comment]
Bot will check the amount of balls you selected to keep.
Let's say you wanna keep 100 balls but you got 50 pokeballs, 60 greatballs and 70 ultraballs.
It will keep your 100 best balls -> 70 ultraballs and 30 greatballs but it will recycle 50 pokeballs and 30 greatballs 

There's really no need to config each individual amount since it always keeps your best.

**Comment by chinpun** [comment]
Thank you, i did not realize that the bot keep the better ones. Thanks for the fast answer and good job with the bot
