### ISSUE TITLE
Necrobot throws away pokemon with more than specified CP or IV

### ISSUE THREAD

**Issue by WishmasterNano** [NECROBOTIO/NecroBot#4155]
So I ran the bot with sniping, until it hit the max pokemon count.
To get rid of the many Dragonite, Blastois and so on (all which are by default on "PokemonsNotToTransfer") I deleted them from "PokemonsNotToTransfer".

Now the problem:
After i restarted, the bot, it began to send all this duplicats away, starting with the strongest CP! although this pokemons had more Cp than   "KeepMinCp": 1800,
even the ones with more IV than   "KeepMinIvPercentage": 92.0, got sent away

it continued until only one diplicate of each pokemon remaind (the one with the lowest CP)

what i wanted: keep 1 duplicate of each (strongest) + keep everything above 1800 CP or 92% IV

my config: http://pastebin.com/z2c3nCUL

**Comment by Pokemongobottttttt** [comment]
Config link wont work for me.

**Comment by WishmasterNano** [comment]
sry, fixed

**Comment by erikk00** [comment]
text of link is right but link doesn't work. 

Looked ok to me as a noob, only thing I can think of is:

:TransferWeakPokemon": false,

maybe should be true?  Not sure why it didn't keep your mons that met the filter tho.

**Comment by Pokemongobottttttt** [comment]
Just speculating but maybe its the "KeepMinLvl": 20,
Dont see what else could be doing it.

**Comment by Pokemongobottttttt** [comment]
All threads like this get closed and they consider it the users fault. I tested multiple ones and I keep getting the same results as you for the most part.

**Comment by schwartzadev** [comment]
@Pokemongobottttttt we don't close these threads quoting it as the user's fault. We close these because these questions dont belong here. Here iss where bugs and problems with the code should be reported, not troubleshooting a given user's config file.

This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.

**Comment by Pokemongobottttttt** [comment]
@schwartzadev 
It just seems weird that everything in the text file seems ok but its not doing what we want it to do. Is that not possibly a bug?

**Comment by erikk00** [comment]
He's not going to see this.  In my experience they're too busy with open issues, that are obviously code issues, to deal with issues that might be code but might be bad user config and once they close them, they don't go back.  The fact that you're changing the filter and then it happens means it might be a code issue that just hasn't been seen yet by the majority of users.  

I don't know, I'm not going to test it on my account but it seems fairly easily reproducible if it is a code issue.

**Comment by WishmasterNano** [comment]
@Pokemongobottttttt 

I think i found the problem:

Its the `"PokemonsTransferFilter":`  every setting for a specific pokemon under this line is overriding the global settings. The bad thing about this is that the default settings in this filter are pretty harsh for a dragonite for example: 
```
    "Dragonite": {
      "KeepMinCp": 2600,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    }
```

the   `"KeepMinCp": 2600,` is overriding the global setting `"KeepMinCp": 1800,`

so what happend is this:  i had no dragonite over 2600 but a dragonite over IV 90% with lets say 350CP. This 350CP will be kept because it fits the `"KeepMinIvPercentage": 90.0,`. None of the higher ones will be kept because the 350 takes the only  `"KeepMinDuplicatePokemon": 1,` slot and therefor every other dragonite will get sent away

**Comment by erikk00** [comment]
@WishmasterNano I don't think that is the problem (unless the KeepMinOperator variable is broken).  In your example it's set as "or" so it'll match KeepMinIvPercentage of over 90. 

Actually I just realized that you're right, this is the issue. it's because of this bug:

https://github.com/NECROBOTIO/NecroBot/issues/4194

Well possibly also that the PokemonTransferFilter is overriding global but I'm guessing that's working as intended and just a config issue combined with the aforementioned bug.
