### ISSUE TITLE
BOT not catching any pokemon and only visiting pokestops even though my inventory is full 

### ISSUE THREAD

**Issue by dev1lsd0uble** [NECROBOTIO/NecroBot#4234]
### Actual Behavior
not cathing anything.

### Your config.json
```

config and screengrab of bot
http://www.mediafire.com/download/nqeu2h0yr5uq4ni/config_and_screengrab.rar
```

### Steps to Reproduce
not sure, i have tried completely removing the bot and starting again and still get this problem, even after update

### Other Information
Version: 0.8.1
Windows Version: wondows 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): all

**Comment by Sasstraliss** [comment]
I'm also getting this.

**Comment by Majamulli** [comment]
I just checked your config and you set the KeepMinDuplicatePokemon to 3. That means the bot will keep 3 of each pokemon. That would result in almost 350 pokemon without counting those that are being kept because of their CP and IV. So yeah, problem is that your inventory is full and it cant catch any pokemon.

Try to set KeepMinDuplicatePokemon to 1 and you will be able to catch pokemon again.

**Comment by dev1lsd0uble** [comment]
yeah i have 550 slots for pokemon though

**Comment by nfettinger** [comment]
Please use our Discord chat rooms for help with general questions and configuration issues.
