### ISSUE TITLE
Getting a softban and then temporary IP ban with only two bots running. 

### ISSUE THREAD

**Issue by erich91** [NECROBOTIO/NecroBot#4264]
Title explains it. Cant run two bots or even one bot. Ive attached my config file. Wouldn't work last night, this morning it ran for a solid 6 hours, then both went back to a repeated ban cycle/IP ban. I've tried using an IP switcher on different intervals (1 minute, 5 minute, 15, etc) to no avail. I've also posted in discord asking for assistance to no avail as well. I've been using necrobot since it first started and have been very happy with it, but now it doesnt work much more than it does for me. Any insight into the issue would be much appreciated. Changing my IP also does not let me run necrobot, still goes to the famous message "no usable pokestops". When it goes down it tries to unban repeatedly with no luck. I also tried only running one bot, and still get the same issue after only 3-5 minutes of running it. Ive tried it on my server with a different IP (not spoofed) as well, with no luck. I had the speed at 85 KPh, and dropped it to a low 15 KPH. Testing further

My config: http://pasted.co/ef9c27dc

**Comment by popsoda27** [comment]
Since the last update and I quote:
"From a safety standpoint, Pokémon Go is also intensifying its regulations. Now you can no longer attempt a throw at heightened speeds, and you will also have to confirm that you are not driving while playing in a moving vehicle."

While it's a safety feature, can it be said that it may also be a speed check? So maybe you could drop your maxspeed to between 5-10kph to be safe from softbans. Just an opinion since the bot does most of the work anyways

**Comment by erich91** [comment]
I appreciate you taking time to respond. my updated app hasnt verfied that im not driving, but many people are running at and over 100 kph with no issues.

**Comment by popsoda27** [comment]
The app does require a manual button click to verify that you are a passenger instead of a driver and the bot doesn't do that on our behalf so maybe that's their catch? I'm not sure about others but I do get softbans even at 15kph

**Comment by erich91** [comment]
Interesting
