### ISSUE TITLE
Did not find a pokemon within the location, pokemon despawned? Cycling same coordinates 0.8.2

### ISSUE THREAD

**Issue by jimmyjoneser** [NECROBOTIO/NecroBot#4300]
0.8.2 necrobot, 0.1.6 pogofeeder
the bot is still getting stuck in sniper loops that are slowing the bot down, it seems as if now the bot will cycle through channels for sniping, but is still getting stuck on recycling coordinates that are expired. The main problem seems to be with skiplagged.com at the moment, but with the other channels down it's hard to confirm if it's isolated. It's frustrating me mainly because it will snipe occasionally and does still function, but the loops are slowing down the bot's XP/hr and travelling. I have considered turning off the sniper for now, but is this behaviour still known/expected at this point? 
![image](https://cloud.githubusercontent.com/assets/20933036/17543344/8eccc4d0-5eaa-11e6-98be-2b0a9f2d91e1.png)

![image](https://cloud.githubusercontent.com/assets/20933036/17543448/4f1db35c-5eab-11e6-8793-97f6c0793650.png)

**Comment by verecundus** [comment]
I don't know if people continue to have problems with sniping but I finally narrowed down the issue that I was having with not finding pokemon.
With the 8.0 release -
  "DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 2000,
 was changed to -
  "DelayBetweenPlayerActions": 500,
  "DelayBetweenPokemonCatch": 200,

This doesn't give the pogo servers enough time to populate the pokemon you are sniping before sending a no pokemon found result. 

I simply changed my settings back to the 5000 and 2000 and changed 
  "MinDelayBetweenSnipes": 5000,
to 5000 since there is a longer delay between actions

Now I catch 90% of pokemon that show up on pogolocationfeeder

**Comment by jimmyjoneser** [comment]
Mine as of those screenshots:
"DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 1000,
  "MinDelayBetweenSnipes": 70000,

I could try changing delay between catch to 2000, but for now I turned off sniping with skiplagged and now the sniper is basically off completely as there is no real connection to the other servers. However, it beats getting stuck in those loops. Before 0.8.2 and 0.1.6 feeder, I was catching 75% or so. It seems before an update hits, I manage to hit high percentages, and then the update comes out and I drop to about 20% snipe rate, if that. Then I stay on here for hours tweaking and (most likely) accomplishing nothing until it starts having greater and greater success, then update and boom. Has happened every version since 0.7.6, and I have tried every setting imaginable

**Comment by jimmyjoneser** [comment]
when pokewatchers connects it seems to work fine, with a fully online feeder it should be great, I doubt there's a problem with the bot, although the fact that skiplagged was rechecking coords seems kinda odd still though. 
![image](https://cloud.githubusercontent.com/assets/20933036/17544004/13fbd2a0-5eaf-11e6-95fc-fb7ddadfe19b.png)

**Comment by nfettinger** [comment]
Duplicate issue.
