### ISSUE TITLE
After "Error Niantic Servers unstable, throttling API Calls." bot go to start location.

### ISSUE THREAD

**Issue by Hastle31** [NECROBOTIO/NecroBot#4305]
Hey! Sorry for my bad english. 
I use bot with GPXPathing.  But sometimes (every ~40 minuts) bot have error "Error Niantic Servers unstable, throttling API Calls.". And after this error bot going to start (default) location. I want that bot continue going to next GPX destination point. Can you do it? Thank you!
![1](https://cloud.githubusercontent.com/assets/10114668/17543594/60009322-5eda-11e6-9022-3cb6e5ad55d6.png)

**Comment by GraspGG** [comment]
This happened to me as well - several times on several routes - since as long as i can think backwards and with all bot versions. I was guessing the fault had been on my side - anywhere within my .gpx files - until i saw this issue over here. It seems to happen after a certain time: rarely on the same spot, but allways within a small area.

Now reading through the logfiles it turns out that this ALWAYS happens exactly 30 Minutes after the bot starts to take action.

Right after starting the bot it shows the TOP 10 pokemon,
**[17:18:24] ====== Höchste WP ======**
... 
[17:18:26] [Entwicklung] Mögliche Entwicklungen: 1
[17:18:26] Catch 24 more Pokemon to use a Lucky Egg!
... 30 minutes walking, catching, farming, sniping ...
**[17:48:25] Niantic Servers unstable, throttling API Calls.** 
...
Now the bot goes **straight** back to start coordinates (it takes him nearly 5 minutes to reach the start coordinates location) while the next 30 minutes period starts immediately after the "API" happening, cause the next time it occurs was at
...
**[18:18:38] Niantic Servers unstable, throttling API Calls.**

**Comment by Hastle31** [comment]
I agree with GraspGG. I read log files, and this error every 30 minuts.

**Comment by rockycabaero** [comment]
how do you see the map?

**Comment by Hastle31** [comment]
@rockycabaero , https://github.com/nicoschmitt/necrobotvisualizer

**Comment by nfettinger** [comment]
Duplicate issue.
