### ISSUE TITLE
can't login, Please help me guys

### ISSUE THREAD

**Issue by hrrywsh** [NECROBOTIO/NecroBot#4337]
I can't to login,  I have to fill my username and pass in auth.json
anybody can help me
and sorry for my english.. thanks

**Comment by REDDE4D** [comment]
go to config folder and open auth.json and fill it with your login details

**Comment by rachong** [comment]
Just edit your username and password in "auth.json"
Maybe it can help..and make sure your user nama and password is correct

**Comment by BobbyWibowo** [comment]
In addition to that, please learn to read Wiki first.

**Comment by REDDE4D** [comment]
An info for ur future posts. Please Remove your IP and User details on screens. There are many bad People out there.

**Comment by wia204** [comment]
got the same problem - already filled all details in auth.json - im using google.. problem since 20 minutes.. older version of necro got same issue too

**Comment by hrrywsh** [comment]
oh, okay, thanks for information. 
must use "username" "pass"

**Comment by BobbyWibowo** [comment]
@wia204 If the error message was the exact same as that screenshot, spellproof your auth.json and make sure that the file was exactly written as the default config (except your credentials, obviously). Also spellproof the file name. A common mistake that I've seen a lot of people do was renaming the auth.json into auth.json.json because they weren't aware that the file already had .json file type (usually happen on machine with hidden file extension).

**Comment by wia204** [comment]
i forget ".." sorry...

**Comment by torbenw1996** [comment]
i got this error too.
it was working and now it dosent. password not changed

**Comment by ioslalla** [comment]
![2016-08-10 09_16_41-](https://cloud.githubusercontent.com/assets/20943363/17545148/c8d291c4-5edb-11e6-98f2-d71ab24b0a45.png)
I cant login, all time this error...

**Comment by BobbyWibowo** [comment]
Make sure `pgorelease.nianticlabs.com` is not blocked on your machine and check whether the bot is being blocked by firewall.

**Comment by nfettinger** [comment]
It cannot access your VPN or Proxy
