### ISSUE TITLE
Fix Errors with Location Feeder!

### ISSUE THREAD

**Issue by FantasyHuang** [NECROBOTIO/NecroBot#4355]
# necrobot\Config\config.json
"GetSniperInfoFromPokezz": false,
"GetOnlyVerifiedSniperInfoFromPokezz": false,
"GetSniperInfoFromPokeWatchers": false,

# PogoLocationFeeder.GUI.v0.1.6\Config\config.json
"UsePokezz": false,
"UsePokewatchers": false,

**Comment by DariusFoxy** [comment]
This is the settings i was using Huang, because i didn't know what each line meant.

"UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "GetSniperInfoFromPokeSnipers": false,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,

and not using PoGo Feeder.   

if you could help me out i would appreciate it, in knowing what each line does.

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
