### ISSUE TITLE
Transferring all pokemons after 0.8.4. update

### ISSUE THREAD

**Issue by inpsm** [NECROBOTIO/NecroBot#4358]
Hi guys.

After an update to 0.8.4. I've encountered a problem - Necrobot keeps transferring all of my Pokemons. Bye-bye Pinsir CP 950 ;( The pattern seems to be erratic, though - even though said Pinsir has been transferred, both Eevee (CP 500) and Magicarp (CP 120) have not. 

Anyway, I noticed that this problem is usually solved by changing the value of "KeepMinDuplicatePokemon" to "1". Didn't help in my case.  Below you can find  my config. Could you please help me? 
[config.txt](https://github.com/NECROBOTIO/NecroBot/files/410525/config.txt)

**Comment by SebastienBenazet** [comment]
Maybe "TransferWeakPokemon" is set to "True"

**Comment by NoiRequiem** [comment]
Yeah, it seems like the config file keeps getting altered unnecessarily after some update. Best to keep a backup config file that you like.

**Comment by cyanotic** [comment]
there is no "KeepMinDuplicatePokemon" in config file, except in "PokemonsTransferFilter"

**Comment by frendyyuniar** [comment]
@SebastienBenazet whether it has been tested with the arrangement and succeed?

**Comment by FantasyHuang** [comment]
You have to check 
"PokemonsTransferFilter": {
    "Pinsir": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
}

**Comment by Rabelaiss** [comment]
I think this happened to you because of KeepMinDuplicatePokemon set to 0
Dunno why this is 0 on default, should be 1.
There is a problem behind understanding of keepminduplicate meaning.
The question is: KeepMinDuplicatePokemon specifies how many duplicates of each Pokemon to keep or specifies the exact number of pokemon of each ?
The name is tricky and shoul be changed, because if you set it to 1 you may expect to see 1 original + 1 duplicate, so 2 pkm of each type. But actually if you set it to 1 the bot will keep only 1 pkm.

**Comment by padmanek** [comment]
@Rabelaiss the option been always working the same way. It will keep X amount of Pokemon's ON TOP of those that meet the CP or IV requirements. Meaning setting it to 1 will eventually gather you 145 of useless pokes that don't even meet the CP and IV requirements. Been using 0 for weeks now..

**Comment by inpsm** [comment]
@cyanotic - that's it. I've got no idea how it happened - I was checking the value of KeepMinDuplicatePokemon a moment before uploading my config file. 

Apologies and many thanks!

**Comment by Rabelaiss** [comment]
@padmanek put it to 0 is safe only if you know well how to use the config file
If set KeepMinDuplicatePokemon to 0 and you add a filter for a certain pkm, and set iv 100 and cp 4000 and you dont have any pkm of that kind who satisfy one of the two conditions, then the bot will transfer any pkm of that kind, so you will have 0 pkm of that kind.
If you set KeepMinDuplicatePokemon to 1 and try the experiment with another pkm, in the end you will have 1 pkm left of that kind.
I have tried this several times so its true.
The name KeepMinDuplicatePokemon is not correct because the real meaning for the bot is KeepMinPokemon

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
