### ISSUE TITLE
ip ban, also ban when use vpn

### ISSUE THREAD

**Issue by 1833233** [NECROBOTIO/NecroBot#4375]
It's problem in 0.8.4

**Comment by bastacs** [comment]
AUTO BANNED OMG I DONE :D

**Comment by AceTotem** [comment]
Permanent ban? Is that a thing in PoGo?

**Comment by jemrick** [comment]
are we done? huhuhuh

**Comment by bastacs** [comment]
just ip banned :D try with another provider :)

**Comment by phoojunior** [comment]
in sydney.. cant bot?

no one pokestop.. can u tell me why?

**Comment by bastacs** [comment]
bot v 8.4 is broke

**Comment by yonrin** [comment]
I have a problem which happens after around 1 min. It says pokemon go servers are unstable and it is hard to make a connection. Then bot restarts, but i can still catch pokemon etc etc

**Comment by jemrick** [comment]
i made another account but still theres no pokestop or gym at all? is pokemon go server is down? philippines here

**Comment by yonrin** [comment]
it might. I have some issues with the connection to servers, but since you made a fresh account i think pokemon go is just down. Might be some big changes within pokemon go today, so i suggest you wait until you hear more from the developer.


________________________________
Fra: jemrick <notifications@github.com>
Sendt: 10. august 2016 10:28
Til: NECROBOTIO/NecroBot
Kopi: yonrin; Comment
Emne: Re: [NECROBOTIO/NecroBot] ip ban, also ban when use vpn (#4375)


i made another account but still theres no pokestop or gym at all? is pokemon go server is down? philippines here

-

**Comment by 1833233** [comment]
0.8.5 fix it now, guys update!

**Comment by jemrick** [comment]
i updated but im having this error. Connection refused. Your ip might have been blacklisted by niantic. exiting

**Comment by 1833233** [comment]
But after 5 mins, got ban again

**Comment by yonrin** [comment]
niantic banning ip adresses are just stupid because of many hotspots in popular areas. Just something from your side i think

**Comment by yonrin** [comment]
@1833233 what did the message say when you got "banned"?

**Comment by johnberr112** [comment]
can i change my ip using necrobot?

**Comment by yonrin** [comment]
@johnberr112 no

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
