### ISSUE TITLE
V8.5 is removing all pokemon

### ISSUE THREAD

**Issue by repelsteeltjehd** [NECROBOTIO/NecroBot#4427]
Noticed that update 8.5 is transfering all pokemon.. do not use this version be warned.

**Comment by ruchern** [comment]
See your settings properly.

**Comment by pixerx** [comment]
Config.json change to default after update, beware every new update.

**Comment by theloser** [comment]
Config issue. Go to (Discord)[https://discord.gg/VXKxNFr] and ask for help.

**Comment by RobbyYuwono** [comment]
set keepduplicatepokemon to 1

**Comment by repelsteeltjehd** [comment]
i updated from 8.4 to 8.5 and then it started removing all.. damn gotta start grinding again.. thanks

**Comment by lwl1983** [comment]
now exp only 210 for cacth 1 pokemon
no more 210 exp

**Comment by Wardom26** [comment]
How to fix this? i run my config.json on notepad lol

**Comment by theloser** [comment]
This is a config issue. Please go to [Discord](https://discord.gg/VXKxNFr) and ask for help.

**Comment by repelsteeltjehd** [comment]
i changed keepminduplicatepokemon to 1 that fixed the issue for me! thanks Robby

**Comment by kentsang77** [comment]
The wiki page is not clear on how to avoid transferring all pokemons.
Well, I learnt it at version 0.6.4 and now I double check all config after every upgrade.
Setting KeepMinDuplicatePokemon as '1' will keep the most highest CP pokemon. Setting as '0', which is the default value, MAY transfer all of your pokemons, depend on other settings.

Moreover, there are so many people suffer from this parameter. There were so many issues (related to this setting) created in past few days. Many people cried for their pokemons are being transferred. Moderators are busy on checking, replying and closing these duplicated issues.

To Dear Moderators:
Instead of keep closing duplicated issues and ask users to double check config before starting bot, why don't make KeepMinDuplicatePokemon default value as '1'.. or other NON-ZERO values?

As I said before, there isn't a circumstance that user prefer to transfer all pokemons, setting KeepMinDuplicatePokemon = 0 as default value is nonsense.

**Comment by jemrick** [comment]
why my default setting always transfered high level pokemon :( someone help please

**Comment by repelsteeltjehd** [comment]
my high pokemon get transferred to.. i don't get it!

**Comment by theloser** [comment]
This is a config issue. Please go to [Discord](https://discord.gg/VXKxNFr) and ask for help.

**Comment by jemrick** [comment]
its already set to 1 but it keeps on transferring
