### ISSUE TITLE
how many open bot same time?

### ISSUE THREAD

**Issue by daniel87kk** [NECROBOTIO/NecroBot#4476]
how many open bot same time?

**Comment by huCyy** [comment]
you can use 2 at a time.

**Comment by GammaG** [comment]
I think you can have several, but then you should copy the whole package and rename it, since every bot has its own configuration.

**Comment by daniel87kk** [comment]
not softban open 2 bot on same time?

**Comment by kentsang77** [comment]
The softban logic is changing all over the time.
Last morning I can open 3 bots at the same time.
Last night I can open only 2 bots otherwise softban.
Today, I can open only 1 bot and still got softban.
I will try to slow down the speed and see the result.
Every softban I have to wait around 1 hour to be unbaned

**Comment by huCyy** [comment]
@daniel87kk 2 works fine for me. no problem at all.

**Comment by HEISEN3E2G** [comment]
@huCyy for me just 1, when i run 2 acc get ban ;(

**Comment by claudionores** [comment]
same here guys, can open only one acc at a time, 1 was using 3 acc last week. makes sense since youre accessing many account at the same time on the same "device".
