### ISSUE TITLE
IP softban?

### ISSUE THREAD

**Issue by Indomin0us** [NECROBOTIO/NecroBot#4925]
![fullsizerender](https://cloud.githubusercontent.com/assets/20961504/17578348/b99039e4-5f55-11e6-9d7a-6d4def3827bf.jpg)
What is this, how does it happen, how do I fix it?

**Comment by Rick058** [comment]
Turn Wi-Fi off, get on 3g/4g and restart the app. Probably IP banned however, cellular data still works. Have the same issue here at home.

**Comment by Indomin0us** [comment]
What if I just disable location services for the app? Would that work?

**Comment by Rick058** [comment]
Well then you get an empty map, that does not make sense. 
Your problem is that you don't see any Pokestops or Gyms on your phone while your account is working fine, this is because you are most likely on the same Wi-Fi as on which you used the bot on aka you are IP banned. Therefor I said try playing on cellular data (3g/4g) instead as that worked for me since you are playing under a new IP.

**Comment by Indomin0us** [comment]
Ok that makes sense. Thanks

**Comment by jumpcom** [comment]
maybe countryban

**Comment by brightjoyy** [comment]
or you just restart your rounter

**Comment by Indomin0us** [comment]
I'm just gonna use vpn
