### ISSUE TITLE
[Question] Transferring

### ISSUE THREAD

**Issue by petpetpetvm** [NECROBOTIO/NecroBot#5154]
I just want to know how to make the bot keep pokemons that are over 2000cp or 90IV only (for all pokemon)?
Thanks

**Comment by ausscheider** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki

**Comment by Linewalker** [comment]
No code, but config issue, please close.

**Comment by Pokemongobottttttt** [comment]
You want it to only keep pokemon that have 2000cp AND 90IV together? or as individual values?

**Comment by petpetpetvm** [comment]
Or

**Comment by Pokemongobottttttt** [comment]
"KeepMinCp": 2000,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 0,

Make sure that keep min duplicate pokemon is a 0. Otherwise itll keep 1 of everything reguardless of iv/cp

Also go through the transfer list of individual pokemon and make none of the values conflict with the ones above, otherwise itll keep them. let me know if you dont know what I mean.

**Comment by Pokemongobottttttt** [comment]
side note: some pokemon do not ever reach 2000cp so it will never worry about their cp and only keep them based of IV. This is what the lower Pokemon specific vales are useful for.  If you care about any of them, add them to the transfer list using this as a guide for their max CP.

http://gearnuke.com/pokemon-go-max-cp-pokemon-pokemon-go/

Keep in mind, these numbers are based off a 100IV maxed out pokemon. So dont be too close to the max value or you may never keep a high CP one.

**Comment by petpetpetvm** [comment]
that's ok, that's why i use "or"

**Comment by Pokemongobottttttt** [comment]
Cloyster max CP = 2052.85

You will never find a cloyster with 2k CP. So it will just go off IV specifically. It will toss an 1800 CP with 89 IV for a 200 CP 90IV. Im sure you get the point, just wanted to use a specific example.

**Comment by petpetpetvm** [comment]
Thanks i will take the 200 cp 90IV then haha, thanks so much
