### ISSUE TITLE
Why Pokesnipe stop

### ISSUE THREAD

**Issue by Fremder** [NECROBOTIO/NecroBot#5230]
My PokeSnipe using "PogoLocationFeeder" just stops he catch some pokemons and last message "Sniping Relaxo ..." And thats all.

**Comment by Adenahmed** [comment]
"UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,
  "MinPokeballsToSnipe": 100,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 70000,
  "SnipingScanOffset": 0.013,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,

Try this instead of using the pogolocationfeeder.

**Comment by Adenahmed** [comment]
"UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,
  "MinPokeballsToSnipe": 100,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 70000,
  "SnipingScanOffset": 0.013,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,

Try using this instead of the pogolocationfeeder

**Comment by Linewalker** [comment]
PogoLocationFeeder issue, please refeer to PogoLocationFeeder and close issue.
