### ISSUE TITLE
Files missing from ZIP

### ISSUE THREAD

**Issue by mgwalm** [NECROBOTIO/NecroBot#5282]
I'm trying to bid on this project in Freelancer. I downloaded the ZIP today (12/08/2016) and FeroxRev and POGOProtos folders are both empty.

**Comment by Bananab0y** [comment]
That is because the two folders are from repositories different than this one (NECROBOTIO/NecroBot).
FeroxRev is from [NECROBOTIO/Necrobot-Rocket-API](https://github.com/NECROBOTIO/NecroBot-Rocket-API/tree/d4c03e752a4114b981e514c28aff124c4f142e3e) , and POGOProtos is from [NECROBOTIO/POGOProtos-0.31.0](https://github.com/NECROBOTIO/POGOProtos-0.31.0/tree/40d334ca496020863fdd0675eb2b1f322e7af428)

**Comment by mgwalm** [comment]
Ok, thanks.
