### ISSUE TITLE
Certain Pokemon not Transferring

### ISSUE THREAD

**Issue by Caellum88** [NECROBOTIO/NecroBot#5302]
Hi, I tried asking in Discord for help but I'm not able to get any assistance, can anybody please help me with my config? My issue is certain pokemon are not being transferred even below IV/CP mins. Also, some entries in my "PokemonsTransferFilter" are not being followed as well:

Screenshot:
http://imgur.com/a/XRc73
(The Electrodes are not on my PokemonsTransferFilter list, Gyarados is)

http://pastebin.com/Qkvjp7kG

**Comment by Rick058** [comment]
I think it has to do with the line
`  "KeepPokemonsThatCanEvolve": true,`
Due to Electrode is able to evolve into a Voltorb, where-as your settings as configured to start evolving as soon as your Pokémon inventory hits 50% (so 125/250) `  "EvolveKeptPokemonsAtStorageUsagePercentage": 50.0,`

Rest seems fine to me.

**Comment by Caellum88** [comment]
Thank for replying Rick058, I tried changing that (50->10) it's still the same unfortunately :(
