### ISSUE TITLE
Either bug or config error, not sure

### ISSUE THREAD

**Issue by g00tch** [NECROBOTIO/NecroBot#5465]
No matter what I do in my config, only Spearows and Shellders transfer.

I've made sure the ones I want transferred aren't on my NOT list.
KeepMinCP - 600 (I have about 75 pokemon under 600 from farming currently that should be auto transferred).
Added them to the TransferFilter and set all the Keep stats to levels that those pokemon can't reach.

Anyone else having this problem?

**Comment by headhunter1215** [comment]
did you turn off auto evolving pokemon and keep pokemon that can evolve?

**Comment by g00tch** [comment]
Yup. I do all evolving manually.

**Comment by headhunter1215** [comment]
yes but did you also set keep pokemon that can evolve to false?

**Comment by g00tch** [comment]
Ah ha! Thanks!

**Comment by headhunter1215** [comment]
Np :)

**Comment by Caterpee** [comment]
I've put every pokemon in the PokemonsTransferFilter which is huge list but never let me down. I just copy the whole thing to each new version. It's working fine to me since with many versions there is trouble with changing global default settings and people losing all their pokemon because some joker set KeepMinDuplicatePokemon to 0 by default.

Otherwise you may check these settings.

  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 3,

**Comment by recon88** [comment]
For help or configuration issues visit https://discord.gg/VXKxNFr
