### ISSUE TITLE
failed to get game data from the server

### ISSUE THREAD

**Issue by osmankudu** [NECROBOTIO/NecroBot#5492]
This "failed to get player information from the server" error is perma ban ?

I cant reach my account.

I tried PTC login is lvl 4 :+1: 

Does anyone have any information about this issues?

**Comment by ipkpeople** [comment]
Anyone who botted yesterday will get either of these 3perma bans : 1. No pokestops (cant spin but can catch pokemons) 2. No Pokemonst (can spin pokestops but cannot catch pokemon) 3. Could not log in at all (death of an account)

**Comment by osmankudu** [comment]
I opened a new account lvl 10 :/

this is very bad

**Comment by Bananab0y** [comment]
@ipkpeople source?

**Comment by ipkpeople** [comment]
@Bananab0y From multiple bot discord channel. Haxton Bot discord has been closed until further notices because of widespread perma bans.

**Comment by headhunter1215** [comment]
@ipkpeople  most of that sounds more like server issues then bans to me except the ones who can't login

**Comment by ipkpeople** [comment]
@headhunter1215 It is not server issues, tested with multiple accounts. If it was server issues you won't be getting those random types of bans. It is a new soft ban and we don't know how long it will last, my first bot account has reach more than 10 hours and it hasn't been lifted. It is a new perma soft bans. Every bot discord channel is talking about it (Haxton Bot channel closed because of that and discontinued).

**Comment by recon88** [comment]
Server issues or ban
