### ISSUE TITLE
Hot Fix Required for Softbans.

### ISSUE THREAD

**Issue by notRayyan** [NECROBOTIO/NecroBot#5524]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
Yes.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
There is but they have not included a fix.

3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Expected Behavior
Unsoftban Account.

### Actual Behavior
Doesn't get unsoftbanned.

### Your config.json
```
your config here
```

### Steps to Reproduce
Get soft banned and run Necro.

This can be fixed by spinning the Pokéstop more than 45 times, it needs to be spun until EXP is gained.

Tested with QuickSpin and problem is solved.

http://pastebin.com/Kt1Pd0S4

This would create soft ban loop on Necro.

HOT FIX REQUIRED.

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by yonrin** [comment]
This is most likely because Niantic checks what lat and lon you have and compare that to your geoip (your location ip adress). If you say you are in america with the bot, but your geoip says you are in Italy, you will get a softbann loop. Use Hotspot shield and choose the country your bot is in, turn it on, and no problem. https://www.hotspotshield.com/

**Comment by Wcidd** [comment]
Dupe #5520
Spins will be increaced in next release
